baseURL = 'https://staging--incredibleedibleloughborough.netlify.app/'
languageCode = 'en-gb'
title = 'Incredible Edible Loughborough'
disableKinds = ['taxonomy', 'term']
ignoreLogs = ['warning-goldmark-raw-html']
enableRobotsTXT = true

[minify]
  minifyOutput = true

[params]
  shortTitle = "IEL"
  contactEmailAddress = "info@edibleloughborough.org.uk"
  breakpointXl = "1260px"
  breakpointLg = "992px"
  breakpointMd = "768px"
  breakpointSm = "576px"
  author.name = "Michael Fraser"

[menu]
  [[menu.main]]
    name = 'Home'
    url = '/'
    weight = 1
  [[menu.main]]
    name = 'Our Gardens'
    url = '/our-gardens/'
    weight = 2
  [[menu.main]]
    name = 'Get Involved'
    url = '/get-involved/'
    weight = 3
  [[menu.main]]
    name = 'Contact Us'
    url = '/contact-us/'
    weight = 4
